using Microsoft.EntityFrameworkCore.Migrations;

namespace SafariAPI.Migrations
{
    public partial class init2 : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "PokeLogsSql",
                columns: table => new
                {
                    id = table.Column<int>(nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    userId = table.Column<int>(nullable: false),
                    Bulbasaur = table.Column<bool>(nullable: false),
                    Ivysaur = table.Column<bool>(nullable: false),
                    Venusaur = table.Column<bool>(nullable: false),
                    Charmander = table.Column<bool>(nullable: false),
                    Charmeleon = table.Column<bool>(nullable: false),
                    Charizard = table.Column<bool>(nullable: false),
                    Squirtle = table.Column<bool>(nullable: false),
                    Wartortle = table.Column<bool>(nullable: false),
                    Blastoise = table.Column<bool>(nullable: false),
                    Caterpie = table.Column<bool>(nullable: false),
                    Metapod = table.Column<bool>(nullable: false),
                    Butterfree = table.Column<bool>(nullable: false),
                    Weedle = table.Column<bool>(nullable: false),
                    Kakuna = table.Column<bool>(nullable: false),
                    Beedrill = table.Column<bool>(nullable: false),
                    Pidgey = table.Column<bool>(nullable: false),
                    Pidgeotto = table.Column<bool>(nullable: false),
                    Pidgeot = table.Column<bool>(nullable: false),
                    Rattata = table.Column<bool>(nullable: false),
                    Raticate = table.Column<bool>(nullable: false),
                    Spearow = table.Column<bool>(nullable: false),
                    Fearow = table.Column<bool>(nullable: false),
                    Ekans = table.Column<bool>(nullable: false),
                    Arbok = table.Column<bool>(nullable: false),
                    Pikachu = table.Column<bool>(nullable: false),
                    Raichu = table.Column<bool>(nullable: false),
                    Sandshrew = table.Column<bool>(nullable: false),
                    Sandslash = table.Column<bool>(nullable: false),
                    NidoranF = table.Column<bool>(nullable: false),
                    Nidorina = table.Column<bool>(nullable: false),
                    Nidoqueen = table.Column<bool>(nullable: false),
                    NidoranM = table.Column<bool>(nullable: false),
                    Nidorino = table.Column<bool>(nullable: false),
                    Nidoking = table.Column<bool>(nullable: false),
                    Clefairy = table.Column<bool>(nullable: false),
                    Clefable = table.Column<bool>(nullable: false),
                    Vulpix = table.Column<bool>(nullable: false),
                    Ninetales = table.Column<bool>(nullable: false),
                    Jigglypuff = table.Column<bool>(nullable: false),
                    Wigglytuff = table.Column<bool>(nullable: false),
                    Zubat = table.Column<bool>(nullable: false),
                    Golbat = table.Column<bool>(nullable: false),
                    Oddish = table.Column<bool>(nullable: false),
                    Gloom = table.Column<bool>(nullable: false),
                    Vileplume = table.Column<bool>(nullable: false),
                    Paras = table.Column<bool>(nullable: false),
                    Parasect = table.Column<bool>(nullable: false),
                    Venonat = table.Column<bool>(nullable: false),
                    Venomoth = table.Column<bool>(nullable: false),
                    Diglett = table.Column<bool>(nullable: false),
                    Dugtrio = table.Column<bool>(nullable: false),
                    Meowth = table.Column<bool>(nullable: false),
                    Persian = table.Column<bool>(nullable: false),
                    Psyduck = table.Column<bool>(nullable: false),
                    Golduck = table.Column<bool>(nullable: false),
                    Mankey = table.Column<bool>(nullable: false),
                    Primeape = table.Column<bool>(nullable: false),
                    Growlithe = table.Column<bool>(nullable: false),
                    Arcanine = table.Column<bool>(nullable: false),
                    Poliwag = table.Column<bool>(nullable: false),
                    Poliwhirl = table.Column<bool>(nullable: false),
                    Poliwrath = table.Column<bool>(nullable: false),
                    Abra = table.Column<bool>(nullable: false),
                    Kadabra = table.Column<bool>(nullable: false),
                    Alakazam = table.Column<bool>(nullable: false),
                    Machop = table.Column<bool>(nullable: false),
                    Machoke = table.Column<bool>(nullable: false),
                    Machamp = table.Column<bool>(nullable: false),
                    Bellsprout = table.Column<bool>(nullable: false),
                    Weepinbell = table.Column<bool>(nullable: false),
                    Victreebell = table.Column<bool>(nullable: false),
                    Tentacool = table.Column<bool>(nullable: false),
                    Tentacruel = table.Column<bool>(nullable: false),
                    Geodude = table.Column<bool>(nullable: false),
                    Graveler = table.Column<bool>(nullable: false),
                    Golem = table.Column<bool>(nullable: false),
                    Ponyta = table.Column<bool>(nullable: false),
                    Rapidash = table.Column<bool>(nullable: false),
                    Slowpoke = table.Column<bool>(nullable: false),
                    Slowbro = table.Column<bool>(nullable: false),
                    Magnemite = table.Column<bool>(nullable: false),
                    Magneton = table.Column<bool>(nullable: false),
                    Farfetchd = table.Column<bool>(nullable: false),
                    Doduo = table.Column<bool>(nullable: false),
                    Dodrio = table.Column<bool>(nullable: false),
                    Seel = table.Column<bool>(nullable: false),
                    Dewgong = table.Column<bool>(nullable: false),
                    Grimer = table.Column<bool>(nullable: false),
                    Muk = table.Column<bool>(nullable: false),
                    Shellder = table.Column<bool>(nullable: false),
                    Cloyster = table.Column<bool>(nullable: false),
                    Gastly = table.Column<bool>(nullable: false),
                    Haunter = table.Column<bool>(nullable: false),
                    Gengar = table.Column<bool>(nullable: false),
                    Onix = table.Column<bool>(nullable: false),
                    Drowzee = table.Column<bool>(nullable: false),
                    Hypno = table.Column<bool>(nullable: false),
                    Krabby = table.Column<bool>(nullable: false),
                    Kingler = table.Column<bool>(nullable: false),
                    Voltorb = table.Column<bool>(nullable: false),
                    Electrode = table.Column<bool>(nullable: false),
                    Exeggcute = table.Column<bool>(nullable: false),
                    Exeggutor = table.Column<bool>(nullable: false),
                    Cubone = table.Column<bool>(nullable: false),
                    Marowak = table.Column<bool>(nullable: false),
                    Hitmonlee = table.Column<bool>(nullable: false),
                    Hitmonchan = table.Column<bool>(nullable: false),
                    Lickitung = table.Column<bool>(nullable: false),
                    Koffing = table.Column<bool>(nullable: false),
                    Weezing = table.Column<bool>(nullable: false),
                    Rhyhorn = table.Column<bool>(nullable: false),
                    Rhydon = table.Column<bool>(nullable: false),
                    Chansey = table.Column<bool>(nullable: false),
                    Tangela = table.Column<bool>(nullable: false),
                    Kangaskhan = table.Column<bool>(nullable: false),
                    Horsea = table.Column<bool>(nullable: false),
                    Seadra = table.Column<bool>(nullable: false),
                    Goldeen = table.Column<bool>(nullable: false),
                    Seaking = table.Column<bool>(nullable: false),
                    Staryu = table.Column<bool>(nullable: false),
                    Starmie = table.Column<bool>(nullable: false),
                    MrMime = table.Column<bool>(nullable: false),
                    Scyther = table.Column<bool>(nullable: false),
                    Jynx = table.Column<bool>(nullable: false),
                    Electabuzz = table.Column<bool>(nullable: false),
                    Magmar = table.Column<bool>(nullable: false),
                    Pinsir = table.Column<bool>(nullable: false),
                    Tauros = table.Column<bool>(nullable: false),
                    Magikarp = table.Column<bool>(nullable: false),
                    Gyarados = table.Column<bool>(nullable: false),
                    Lapras = table.Column<bool>(nullable: false),
                    Ditto = table.Column<bool>(nullable: false),
                    Eevee = table.Column<bool>(nullable: false),
                    Vaporeon = table.Column<bool>(nullable: false),
                    Jolteon = table.Column<bool>(nullable: false),
                    Flareon = table.Column<bool>(nullable: false),
                    Porygon = table.Column<bool>(nullable: false),
                    Omanyte = table.Column<bool>(nullable: false),
                    Omastar = table.Column<bool>(nullable: false),
                    Kabuto = table.Column<bool>(nullable: false),
                    Kabutops = table.Column<bool>(nullable: false),
                    Aerodactyl = table.Column<bool>(nullable: false),
                    Snorlax = table.Column<bool>(nullable: false),
                    Articuno = table.Column<bool>(nullable: false),
                    Zapdos = table.Column<bool>(nullable: false),
                    Moltres = table.Column<bool>(nullable: false),
                    Dratini = table.Column<bool>(nullable: false),
                    Dragonair = table.Column<bool>(nullable: false),
                    Dragonite = table.Column<bool>(nullable: false),
                    Mewtwo = table.Column<bool>(nullable: false),
                    Mew = table.Column<bool>(nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_PokeLogsSql", x => x.id);
                });

            migrationBuilder.InsertData(
                table: "PokeLogsSql",
                columns: new[] { "id", "Abra", "Aerodactyl", "Alakazam", "Arbok", "Arcanine", "Articuno", "Beedrill", "Bellsprout", "Blastoise", "Bulbasaur", "Butterfree", "Caterpie", "Chansey", "Charizard", "Charmander", "Charmeleon", "Clefable", "Clefairy", "Cloyster", "Cubone", "Dewgong", "Diglett", "Ditto", "Dodrio", "Doduo", "Dragonair", "Dragonite", "Dratini", "Drowzee", "Dugtrio", "Eevee", "Ekans", "Electabuzz", "Electrode", "Exeggcute", "Exeggutor", "Farfetchd", "Fearow", "Flareon", "Gastly", "Gengar", "Geodude", "Gloom", "Golbat", "Goldeen", "Golduck", "Golem", "Graveler", "Grimer", "Growlithe", "Gyarados", "Haunter", "Hitmonchan", "Hitmonlee", "Horsea", "Hypno", "Ivysaur", "Jigglypuff", "Jolteon", "Jynx", "Kabuto", "Kabutops", "Kadabra", "Kakuna", "Kangaskhan", "Kingler", "Koffing", "Krabby", "Lapras", "Lickitung", "Machamp", "Machoke", "Machop", "Magikarp", "Magmar", "Magnemite", "Magneton", "Mankey", "Marowak", "Meowth", "Metapod", "Mew", "Mewtwo", "Moltres", "MrMime", "Muk", "Nidoking", "Nidoqueen", "NidoranF", "NidoranM", "Nidorina", "Nidorino", "Ninetales", "Oddish", "Omanyte", "Omastar", "Onix", "Paras", "Parasect", "Persian", "Pidgeot", "Pidgeotto", "Pidgey", "Pikachu", "Pinsir", "Poliwag", "Poliwhirl", "Poliwrath", "Ponyta", "Porygon", "Primeape", "Psyduck", "Raichu", "Rapidash", "Raticate", "Rattata", "Rhydon", "Rhyhorn", "Sandshrew", "Sandslash", "Scyther", "Seadra", "Seaking", "Seel", "Shellder", "Slowbro", "Slowpoke", "Snorlax", "Spearow", "Squirtle", "Starmie", "Staryu", "Tangela", "Tauros", "Tentacool", "Tentacruel", "Vaporeon", "Venomoth", "Venonat", "Venusaur", "Victreebell", "Vileplume", "Voltorb", "Vulpix", "Wartortle", "Weedle", "Weepinbell", "Weezing", "Wigglytuff", "Zapdos", "Zubat", "userId" },
                values: new object[] { 1, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, 1 });

            migrationBuilder.InsertData(
                table: "PokeLogsSql",
                columns: new[] { "id", "Abra", "Aerodactyl", "Alakazam", "Arbok", "Arcanine", "Articuno", "Beedrill", "Bellsprout", "Blastoise", "Bulbasaur", "Butterfree", "Caterpie", "Chansey", "Charizard", "Charmander", "Charmeleon", "Clefable", "Clefairy", "Cloyster", "Cubone", "Dewgong", "Diglett", "Ditto", "Dodrio", "Doduo", "Dragonair", "Dragonite", "Dratini", "Drowzee", "Dugtrio", "Eevee", "Ekans", "Electabuzz", "Electrode", "Exeggcute", "Exeggutor", "Farfetchd", "Fearow", "Flareon", "Gastly", "Gengar", "Geodude", "Gloom", "Golbat", "Goldeen", "Golduck", "Golem", "Graveler", "Grimer", "Growlithe", "Gyarados", "Haunter", "Hitmonchan", "Hitmonlee", "Horsea", "Hypno", "Ivysaur", "Jigglypuff", "Jolteon", "Jynx", "Kabuto", "Kabutops", "Kadabra", "Kakuna", "Kangaskhan", "Kingler", "Koffing", "Krabby", "Lapras", "Lickitung", "Machamp", "Machoke", "Machop", "Magikarp", "Magmar", "Magnemite", "Magneton", "Mankey", "Marowak", "Meowth", "Metapod", "Mew", "Mewtwo", "Moltres", "MrMime", "Muk", "Nidoking", "Nidoqueen", "NidoranF", "NidoranM", "Nidorina", "Nidorino", "Ninetales", "Oddish", "Omanyte", "Omastar", "Onix", "Paras", "Parasect", "Persian", "Pidgeot", "Pidgeotto", "Pidgey", "Pikachu", "Pinsir", "Poliwag", "Poliwhirl", "Poliwrath", "Ponyta", "Porygon", "Primeape", "Psyduck", "Raichu", "Rapidash", "Raticate", "Rattata", "Rhydon", "Rhyhorn", "Sandshrew", "Sandslash", "Scyther", "Seadra", "Seaking", "Seel", "Shellder", "Slowbro", "Slowpoke", "Snorlax", "Spearow", "Squirtle", "Starmie", "Staryu", "Tangela", "Tauros", "Tentacool", "Tentacruel", "Vaporeon", "Venomoth", "Venonat", "Venusaur", "Victreebell", "Vileplume", "Voltorb", "Vulpix", "Wartortle", "Weedle", "Weepinbell", "Weezing", "Wigglytuff", "Zapdos", "Zubat", "userId" },
                values: new object[] { 2, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, 2 });
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "PokeLogsSql");
        }
    }
}
